Improve FindCACTUS
lpetre-ulb/gembuild pull request #8
Opened 2019-03-12 21:58 UTC by lmoureaux

Bring it to the same level as FindxDAQ

2019-03-18 23:49 UTC, lpetre-ulb requested changes
I think small adjustments are needed. If I'm mistaken, I'll be happy to approve the PR.

2019-03-18 23:49 UTC, lpetre-ulb commented on FindCACTUS.cmake
> +_cactus_library(amc13_tools HEADER "amc13/AMC13.hh" DEPENDS amc13_amc13)
Are you sure that `amc13/AMC13.hh` is the header file for `amc13_tools` ? The source code and the RPM do not install any header file for the AMC13 tools library. Is your code able to handle such case ?

2019-03-18 23:49 UTC, lpetre-ulb commented on FindCACTUS.cmake
> +_cactus_library(amc13_amc13 HEADER "amc13/AMC13Simple.hh")
The two AMC13 libraries do not have their SONAME set, so I think the option should be added.

2019-03-18 23:49 UTC, lpetre-ulb commented on FindCACTUS.cmake
> +# i2o requires an additional definition
Does CACTUS need and/or provide `i2o` ? Aren't these line a leftover from `xDAQ` ?

2019-03-18 23:49 UTC, lpetre-ulb commented on FindCACTUS.cmake
> +    set(cactus_${name}_depends ${ARG_DEPENDS})
Don't you also need to set `cactus_${name}_header` for the header files ?

2019-03-19 00:10 UTC, lmoureaux commented on FindCACTUS.cmake
> +_cactus_library(amc13_tools HEADER "amc13/AMC13.hh" DEPENDS amc13_amc13)
How would one compile against a library without the corresponding headers? But `AMC13.hh` is indeed wrong.

2019-03-19 00:29 UTC, lpetre-ulb commented on FindCACTUS.cmake
> +_cactus_library(amc13_tools HEADER "amc13/AMC13.hh" DEPENDS amc13_amc13)
I have absolutely no idea... Can't `amc13_tools` be an internal library which is not supposed to be linked to by external binaries ? In the GEMs, I have already seen libraries whose headers must be copied in every source tree... :-/

2019-03-23 18:28 UTC, lmoureaux commented on FindCACTUS.cmake
> +_cactus_library(amc13_tools HEADER "amc13/AMC13.hh" DEPENDS amc13_amc13)
`amc13_tools` is not required by `cmsgemos`.

2019-03-23 18:30 UTC, lmoureaux commented
Rebased and addressed your remarks.

2019-03-24 16:46 UTC, lpetre-ulb approved these changes

2019-03-24 16:47 UTC, merged

2019-03-24 16:48 UTC, lpetre-ulb commented
> Rebased and addressed your remarks.

And more. ;-) Thanks !